### ISSUE TITLE
CSV con ; a  TSV ? 

### ISSUE THREAD

**Issue by ahmad88me** [oeg-upm/website#14]
https://docs.github.com/en/github/managing-files-in-a-repository/rendering-csv-and-tsv-data

**Comment by ocorcho** [comment]
It will really depend on the tool support that the KG creation tool to be used will need to use. CCing @dachafra to check

**Comment by dachafra** [comment]
@ArenasGuerreroJulian can morph-kgc parse csv with `;`? or should they be `,`?

The problem is the use of excel to modify these files, I would recommend to use google spreadsheets as it export CSV with `,` and in UTF-8 @LauCamacho

**Comment by ArenasGuerreroJulian** [comment]
Morph-KGC relies on Pandas, it is very easy to add a delimiter parameter, indicating which character to use as separator. It is possible to read excels as well.

**Comment by ahmad88me** [comment]
It is mainly to make it easy to see the data on GitHub. It might also be easier for others to open.

**Comment by LauCamacho** [comment]
@dachafra Thanks a lot for the suggestion. 
Editing in google spreadsheets and saving them in csv, we can visualize them correctly now.

**Comment by ahmad88me** [comment]
thanks everyone 👍🏼
